[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d33fbb984afeca62a92bcd3ca1aa68397d636b31"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "e4f0088ad817cafd37db47a30176ae0aee523d1146adbc210a3ee9825da08779"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725250e6d9210029e234dcdb11d81c87f1abebb1"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "8a1f2347d22933b959bde0caa1bce11e9c65caad1d9254934b3270e2e080654b"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74e984f7713667cf74f41b9313133039e18e3788"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "63d8150dd608539c41bcc871bcd846c34877af03e32ad07fdca420565b13317f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13aa6cba45447d0cb128510cfe2ece2ff84a095e"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "43fb1b23f4dca2c18aa4c80ef6803fc5de12ee8d65603aeb5ccabff669f5d0eb"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f43013792515970a586d74c7a407b182ea558a58"
os = "macos"

    [[NOMAD.download]]
    sha256 = "0bf08266a529c77de59e42d4eb0088f77893b809705c6f104e962292bc5ecbe9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a4bfd00221a9492c087a8e29623e03a6ad83b60"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "60e00e30ad39c1522bf85a6b03b19c9a1028635dc5069cf28ffa0a1ded133ddd"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6ae65fefd879cf36344b677609797990127b897"
os = "windows"

    [[NOMAD.download]]
    sha256 = "ab704b7cb12658e810d9b358eab7f7371dddf844bbecfb2a4185cc6a33aa7d2a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7b24160c7104868702fc9d232541999d414857a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "190ffc41f1dceac78eae9e34928f8e06f45da303324bc0caefd97c0b95f9c6ee"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57f1ac66554349b2f9e658152d96929860e3243d"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ff0c3de0ba0e4743d0811e00e4d161e7aafa7165ee4e0c23dc21b1856653c1b1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "784943bf33f73299f85af7553f9150a28e38a673"
os = "macos"

    [[NOMAD.download]]
    sha256 = "4744ab887daaaec687e7df9fb3f836e4e6f83ee12e454559266f7865ff9c4f55"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "769251958bdb3686aa1268eca1b677f114a72e6a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "9798ded8245f0c4c47af87cd17b31f3b501a2399d7ea018b32a7b4c76c85a0c6"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "158c99887d2f4bc03cca034afa6181027272d97e"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a865af35af5b3b33f086ffd728625a6f2833dea0612af8733110ec095f386954"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1273fd4d7ceb6f063fde0e7854f2df907b32e92b"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "41dae918c4737b85375d546c24a7d62b59679d45c615e65b78dcfb6d94bed077"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19ff5a1cc3767205a77fb9fdf8d887d3643495ea"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "72c5ea98134d27723f426823b97704c83e59cc16b533c8bb091b9b61ed75d7dd"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9db31dccdfe4c8ea9226effe6364f2daf31bcd5"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "55d9e90ad3e223382ba8a72cf4131c1ecd343337c6990f3ab8515a91331679fe"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "479baf124cd678ecd8eaf42043726903a7ed750d"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "9ca5e7930011fb2417f5dbd2120dd79f9190dacf0d0880331ee51cd8856aa8fb"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb83b5dabe20fde4b2fd06ddd8faeb910b833153"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c0351aa99c11f9bd3efb786dbf09fbee73db2dbb237eecc6da8f10f8807bbf4c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdb4ed3c16ff3c13255ec314756522c56d3483af"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "1b0f265e04103f29bf57491916fd8f4e088716eacbf6b3705ecd9713a808b7c4"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a6b905613cc51ee1a9e592aeaef6ab42b782c40"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "9ec34db8c111e835e84ab44dd7f4e857fa67835c66ed863d12f4e7768bbd1ff4"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18e9a1ddd4ffe260c9ea25c1cdfd64689606ddce"
os = "windows"

    [[NOMAD.download]]
    sha256 = "283f6669f129f0542346a3e020e82dfb648c96d8ed04b5bed55a1910fa9052c8"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df754bfc379cd5abaa300ed164291d26cd1450ab"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b6ad578ed82a961068ef2079f8c931325047718779500232431184862306538d"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be1178db050305429f9bc144b480835f9f72a540"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "2351d5cca660cccef356f25eddb98a54df30563035b46a9fde131c1c39ffa28f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e5937bde10c6599281eef3945632e07313c4aab"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "0ff79ec05cf5742deab15de4639257214c38b930c94a968639bce4760eba67f2"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e782fcb49949334a578a6c704f92e20703ec61f9"
os = "windows"

    [[NOMAD.download]]
    sha256 = "285614a972b7cb3b384bd72d6dfc7305d42fb9ea7b39d7542767f2c2dd35b0ba"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d855d21bd317819a1e8c7616996946d7efdba9e"
os = "windows"

    [[NOMAD.download]]
    sha256 = "928a012dc9a3a80002464817b8ec7e3c409e660a068a376b3deddb17f69851d0"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0da5896e1f97390cee2deb9cb7a28f1f39a0d71e"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "37c15342c986aa9c9661484d7cf1dee74bf503b6900ef5ddcd8a9acc5180a53f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+3/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
