[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e9a52242a038ed75952a25cbc3f9869a7a5eaa6"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "cc6bb46620749c3977b01c8052fd83202284eacdcdde3ca00efb1f5324498793"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbf2b52ef0f28ca9a6bc01babad2c3be45adb3e9"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "0c6dec522ddd56947e9b42c3f93df7b7655113b10fc070652445b91b04bf06d9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8994deda759b76b0f5ed0c31b87d5af964713bf4"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b78f24ef3b6e4ec419a8ef04adacd33f50146877b3261a9039b12ef7b4dd0e11"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bebe52a4c3fd13d781871d29f56e197ea88b5634"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c024897da028401217d673bb73c5ffa8ec2843a1342f3268abac1c02c4622dc7"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f46ba77aa98a57e4cce0c5f01cb0bac7c2f33ae8"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "8cc8e834b6ccf724c605e69eeab89bd8008bbc046f083eb653774d95a9dbcd51"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38738a1290fa035c6b5783cfce2c0fe3af4719bd"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "897b83c346b7b0b50732246242feac9590513624a9f9991a7732418a8ea8895e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5db6f4e394bbd3b42c9dd3fa1d0457b5637cca45"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f41e56792b8a0ad0835e48613134da13f8d0f021b6824a893d113a8c14456b2a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7feea7d67918ace99b6b4c53c194972711130c02"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "d99cf674f0672e84fe3aaa91d3724e08d620985924ede980585ee5e901bd6d51"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54ea52e0692e4ae64fcc5d703529260200bfd653"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "26117dfaecda42664a0480b37dfe2bd889170c587f95d33e1ec6327d9f14cf2e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3021e6e4703d0c1814275307c5bcafd14be90795"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "3f7c5a8c9d094aa1f190f6416ec75e26746041dcf6ba36e6f5569fc123cc73ee"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9e2dcb986786159f18b6c45f7b7a6689181d540"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c28bd8cc8af5744db7ab83c3200a843570d544c84094b452470a2d98c5c4eed9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5e5d6a30f0e96d5127a9f26b71b659738741767"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "58b7c77eedeeef7bfd970eef9ce7df651916ce8514763cf446556c90e16606d1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c8ddd5bb392e21a3f97dfdb8bb03238c5ddbc91"
os = "windows"

    [[NOMAD.download]]
    sha256 = "36e69cd3d4a54bd03472e24d3174a28b5e6467cc5483bf58d6be85ab05d789d1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbf90a2070db8563655937fcdc5f04aba291f8cd"
os = "windows"

    [[NOMAD.download]]
    sha256 = "5ba881c5638e3b737aabf3e1a6d3a233ef5813d6135b986a9b6458485a5b4fad"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "accd8b8cb24e3ff7919ecde435be03d581c0da7f"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "84dc82b555f54d8ddc3e70932683b19e507aa95f3e72a7d27602d73404451827"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6d414be7d2637c0334a10cd00a0080aabcb5443"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a9400483b6b9d2c3a7e5e547824567ce78945638180fc4ce131a6321dc3706d8"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "fd74637ffcf388ffb08c8b69703d573f019feb5e"
os = "macos"

    [[NOMAD.download]]
    sha256 = "9571046c4567a8a80023740ff8f7d81b87b29d7a7e03dc3d04b1dbe43a9d2b0e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-apple-darwin.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd6f35cc9e2aa4190f839dc9458f4fe409319528"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "12f86fae7f1b44fe20bbdc5ccf7eb9ad62e9d798801137589c716b2ad90d232f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9d400ebe8fd97e011c7bbbeb5abca2104503bfc"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ff43d4805c5706d6275b41378826938cc80ede87f7f5d6043ebe7a5454808968"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "067a4fd7b895ab9ae828c1aafad8d283d2393c2f"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "58e78aa060e204f9f704d44da8739dc4ab3842e23dc777ef7fdb0cebd855b1ce"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc4095c9a2cf77aab803ff3d0466d534bad6049e"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "517b458ec8a8cf28946595403c1ac705bd0c851db0cc12aa93db57d5e840bd62"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "e8c7c3c3a0f80ba98e6f3c60cce0509f386f5ea3"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "dcc95702b7dda5d18c220c77ddfd56ff49f3e5d951649eb9dedd3f2f8a55ac59"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-unknown-freebsd.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8d2375d86cbfdc549ba4e8a756c90ce1373a4fb"
os = "windows"

    [[NOMAD.download]]
    sha256 = "5f011b552e4d89cca2a2bdfcad45c12a3a645d54886327aa03b021ef7a62e6bf"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afc55cad05cdd4def2b270e9e0e8261c242e5645"
os = "windows"

    [[NOMAD.download]]
    sha256 = "c750c553afb10d0b205ebdad8c7730b3cf873a03c9bff2e2e716cce0e257d8ea"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+2/NOMAD.v4.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
