[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3a05b3ac4c17b9d2b1f1e72cdacd254ed071ba9"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b01cb5a6c639b9501c3dcfa89c05b1b3791e0cd9f1e593b9ac4d50a35bb34af4"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f119407e73f475f22b6c8c8b2f40b28e99627dbb"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "323e2d6a6f2925441767c92411ce66374f6e8d6911abfe2977d6ce17b9df627a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9589507302f9e4c27ed854c3d9c5ba69c9095055"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "e420aee423e9dc374363829026f3ccff092b6ed2800462716e956c692ee5f832"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41da471d863e4979e20cedf4416ceec5fee36f15"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "fd554411301821d263354cb06423bc18d699211e113adc2792268d8deaa36588"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e085cb61867f2e3db1c027cbac77c025be98daac"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "acb317dfe0f7afeac1f26f4e842dba1684d0cf3c1bba3fc97650b0767e79f115"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "379cf9952c03a3e0816c1f268b991c862f73fde2"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f53b497ec676dd01511c393158b50680220816e092ccae405e248c345c56e6c3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee66496d783aba4cce3cca5ef6e651851cc2f830"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "3351a5cb7aee56a3352368bc0f8fd501f01ba57aae2e01cfb9ad10d5e4f7b213"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b873395ca9b81c48341bf5211233e5885232e97"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "20da5cfccb589df15a3a597867c83ae4109e9902209fa47b932e3e4515f478b8"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa5276ae45806c88302b378dc6f488eee5a765bf"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a6be97e9bd1e4159db1cb4ffdaf319edee483bdc0eeb59c99c8d1866fc01bb24"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d95c9d85772cfea239aceb07d921433dec23cc9"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "251151ef216ee5ae62df02227ef467f9d33f28a4db04fe49df8d644e7c079f9a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0990f7d69002e818cfd76d252bcaa6efd770c86b"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "927d81ad342287621382af8b8dd78ddb32bc806ce86d987a6eb1e4a42761cfc5"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d174cf20887b51756316d9c1f885c83c5369bb8"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "1c5c1b017e6e520f792f3ec19b6abff45ce7eba69124580f7a710cd3fba25a3e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54bf0ab3861970230c6bee75a45dfed6988243b6"
os = "windows"

    [[NOMAD.download]]
    sha256 = "4daf502c373855d4dc37e57c586d39ce4475ebdafb3809609b1169b9d0653594"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3727bc4d6b7d60ef06f2cd623e44bf4296cd036"
os = "windows"

    [[NOMAD.download]]
    sha256 = "7f0195a1b740c2dde55cac5595786cccfbd4ceab335c3863c7a71089af776981"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4e01353308838f3580fdc01900c718ba2d81f65"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f177efb5d6094782c664122fa679f523a2e7dd938cdfc5d1267ed8d9b1cc0e22"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa36c5fd7708b811d2ffb671f60b113ca639f420"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "4ab68df4d680ae9e79c14877541ad7adcf96ae83e46d895b38cf8ef155067be1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25c737f8fa9d977e6d5cde0c0dbca4138b378cae"
os = "macos"

    [[NOMAD.download]]
    sha256 = "41fbacb2b669107a7e1de82e3d0b5ec97b110edc5e949575daac237a868eec2c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fca9c26045c297f594832e8d72c82f2663663e7"
os = "macos"

    [[NOMAD.download]]
    sha256 = "ac569d4460b2eb8207c9345e92e855a4b7d96bbcbd43f2f6f2b4d325b0243c2c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a1937578bd0e7b10bc61e9c9efdbcb691cc936"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "3ec25c5f69402165de444a41c06ac3b302b0598dea6a89911929d18c4ea0ecb9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec291cfa7db013f4be40966ba447de128d5a616a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a1d9ae0a97ee619f0907e245140367067a63669180e49aeb94bc0944c8e90466"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4b7057e735195501bc9eeef05ed7298aa75c158"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "671fc027ad62c2634cf4a1a596c18121c4a83987a96247e1cae00d46fa5aa79d"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47f135fc6aa857b39669eefa323ae080430543d4"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "0272a33084c6b984675e2b2f65f0f5bff6676e144e0c580cd6a122c3f6744554"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2694a7e8c4db9851df0b34ae4732c59dfe63d20"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "a64fb7689f1de5149d907a85c12bb3737272caa7570355ac5b5c56093e12de83"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffd5869226653153fab5edd77ace47183e1c0ef7"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "b12546cffb4b0326e6464fe0cbd396959e80dd7abc7a770cd61301f7e8510d9d"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b902014af1ce1fb1059c426c500742efe82f32ea"
os = "windows"

    [[NOMAD.download]]
    sha256 = "4ac6d5706be494c5c0e033d5e9849a205b6fd8d4cd72d22e8a5893df0a5debfb"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a89ae1e2cba8ec1df9089f035f4871a5bab3158"
os = "windows"

    [[NOMAD.download]]
    sha256 = "d007f389ca16104736eea2dc198a52a0f7b70aa86bece73e68dedffc2a3f7b24"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+5/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
