[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9ee43d260e40b1d457b6971197240898f95353a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f93a27cf90ca6d3f39ccfc28de942871fa1038b1ad5d56c7d4e8561ab41ddfb2"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85083b18a62b7a034405854a752a513c344c0911"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "41c53c008315c5ed2b7555be5611fcd9be568d17243c1ce7439d6961d007e861"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84d10e9c91ec191b9e2dcf0be02c7db6f6933425"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "27115a4bd4428c9ea853f605969ff2d504279bdf2576b788fd29b9303f997af3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d1d42c7577bb3b882798967b601b55f24cbf541"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "42218057485f798228e6c0b62eed2b191d97c0e4ebfce5000319064e5af49c8c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaee99f8da4150519c3d8352da3586502a61c3c4"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a3e47b5579f349385bbe8c7e46c86d1ffbf4afd8ab759aebdcd2e3e8c436c177"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2b36b9d7f02eb17c864038217d034d1f0d163ef"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "915a43c366b841eebceb37a9b00fa6ceaeb1b378fe7a8686b369ed295294ca70"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b0196cd98911b372e81960ac366f78f6d7e6584"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "515e566be8e0c79feca886e4142a04fb370c76797c51fe35dee2cf230e52a4a8"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13b99f05a3ff13a3c7359d6d07025602802c8910"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "7bfba2c201ce54dc5d1fe831e6e1684bf2685464b754eb13a02bca054609c41b"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d19e71b42657a0983d900dfee2854f617c1eed0"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "22f430292b6a5a78fa0def049cda282757a708043111b5702a5ef07f3a4ec2f3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab0b5388eff0ae880754d742a47f6b21052a253f"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "00224fb48e6b364850ac1e3b0a50589a1ef5ce6fe1dc77d1bf9b558819a422c3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bbbf7ec7ac04b480bf59d1bad6d34965ceef287"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "7bcabcffbb61089569fe2c999cff1d1ae4643af4e250c8d169078ad63aa8bf0d"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "369e91390a8aac2412b85866a2eb5338635eb561"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "5486b8e9298174ffa683304acf4c7af97e9c28afe5d9645c89e547dfd6431654"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7018d7518c47bf083e5e39c4f0db8a1decffdf32"
os = "windows"

    [[NOMAD.download]]
    sha256 = "4be2ea2226372e972b2cc0f2a0a9ca1cb53cddd4f19c54b7eb6fe10fe86fc6d1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bba95f7b5a86582a91f5ebc83716274002f54776"
os = "windows"

    [[NOMAD.download]]
    sha256 = "4ca6bd07967624f478e45b55ed9a611dacb470356ef310d5bce77ef5abe1c0e0"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a5bdf15f4f3fe5e064cf39e19cac6d24f6d9926"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "765688f178789676d84655b5c8b8b7d80fbbab48a0422263c452fa903c8727d8"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5f6d7d7b3634f781783cb5839ee5e3775c0219d"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "fc5161990edb96f4fc70d27e73bda9b3453dfb649875f1e89a7da3fd039f119c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "32dc16a3f788d29f3ccd2a2c12adeb83ff3cb7d4"
os = "macos"

    [[NOMAD.download]]
    sha256 = "2cfd58c08c1198887fb6d3add268a5858f9e939453a09e6381351c1a1fcabda0"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-apple-darwin.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a9a8cc0a7a7aa2b99d10e700e818cffed4a418d"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "fe40f44c0db6267fd0ea4a821622ea0e981183335d154ea39cc5192e713db21f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e643b8148bc2882eb4b1c021a411b78b6b61414"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "acf2749299e70d7533d56aea8bb4041914e76670d09cb6314679cfa00430c3cc"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5577b66e4473c7a3bdd34da74697d208491ec6d"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "7b27ece4615b0dd8f6004434e467f6076fde57e723afa2614c4231af65c110ba"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d85320f711f5d57ef875bba151531fcde6ba6fba"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "925887ca1d49956a41f938e024a11db012de4d1c37966418f611c83fefea07ee"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "c6e887e7e9ef7db6256d92acb679212861b9cf42"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "0010d777d09d9f69714aebb9ed7720458dec9259c76d672de6d8f7689f7b4d63"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-unknown-freebsd.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dad8fd52f65d624c904643663196c0c0de5a3413"
os = "windows"

    [[NOMAD.download]]
    sha256 = "63ec1371fe60252a188d50bb4e1952835e8542f352c9270c95d0016cc8842c15"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abdaabc3e137a2b8816230a698248a40a735831a"
os = "windows"

    [[NOMAD.download]]
    sha256 = "6624af29a1fc0d59285eb622b7dccb3b5c09460979b5fbf1ada4a050d2e401d6"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.1+1/NOMAD.v4.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
