[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d0afe75757034ac4f2ab2a1ad7c8bc775d262e7"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "5c5ff15a111e5b4173acaf4cb8bafec6c2a5ea3ee6a9df52c794f9661d468758"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ba0e8ef9af8c2b9fd41aa376e8243d83c04e399"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "928134d6cb1639384351f297339ab448b8602d68ef2298cb080fb1fe8605740e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bced06d777ad6292cc1c0f520fbd49ee8c7efd1e"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "bfaadb5de4549cb8049c5ed90d6fcada0ad95407f205261e1f75ddcf5771813c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac6f0e19325aea4290f2c92150e5494a608c1740"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ea37046d8cd6340dafef2d3690765605cea293de8d046fc1f3833bd420369645"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36c1a6c49625372ca3ebfdfa74a9e596e4ab6e02"
os = "macos"

    [[NOMAD.download]]
    sha256 = "0b1019641d45db0397261f93d9b28e42b041d2186519528945ff78ae8d5956af"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae27509ca248ebadc0e5d26cc06ee5da5e4c6e11"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "e8aa248843dbeb2081a12ea4832bdabe6c4f1c243c0fa4bc848efc9eed2d8b76"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "307ba53ac85d77a0e59abb1966af5333d7b70912"
os = "windows"

    [[NOMAD.download]]
    sha256 = "645aa968d7f1d79912aecbb9f43b24eb5a564aeb2110472c12fa81e7ac73c9bf"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58ca666ee4c068b2518ab3c9e17e905718467c14"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "9066b6dbad41cff7ec201c9d2f151edd8693202c4f6f3c2a47601551ea218060"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed9df849f0e6d1a46f659374b7e49b0a567e41d1"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "1198f3877e92576f269b60f6fd7d4876dc5f29de15f39e0acac540bb390f9534"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "effd29bf295b082d676e291e113dc0339964dd14"
os = "macos"

    [[NOMAD.download]]
    sha256 = "bbe7df454667437e1bbd1f5e3545f226020d1b073fce6d35892ca31283603c9c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d01692a2a644359b7f96cef9bb275347ea7281b3"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f55e32cb91505311b1cc45399d57f20627f263b80830c50748e4dc4768d8cd51"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcfb26dc799ed46862b79da4702e94ae549e4d5f"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "4a993d5677b5854d733095a0b2f7b70f0d47f71b23447bed523b3a131a59d3be"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "913da2544d27f274be213b8ee25f00f9159eada9"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "2d50861f36b94d4be6e4618e83f40960ddd62afaa91452198c4552a6ed5d0f34"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69105187c498d6d20dfdfa39e55696af3dbb6cdc"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "9e4d2525ce4ea5c4dfea9b8721fe78d544bbf32b7a2ff50424940ccbdb0844dc"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9b58941f4fff446c95610261bbae58d034ce835"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "996706a71c287d6f414309b36ea427edccd02308c505a032a2e708afdbb5bc09"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62a9cb31a0dbcb5ea27d420cbf25bff9fbc42cd6"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "eaaecf9b52ed8cd04823c4085bf59ae266046369691f46eca8c21b7b51687ac9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7fa453746268b54f1105002f1d7258313045674"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "7e881f96d0f00970fb8f7def6d4f913ce7bd2eea2f41133d7a6a238981f87e6f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01b554685c07dfa98129c461563c744fd258115c"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ef422e154e21ecd733a5519a77add44cf5fdddc339c90e2f992c018a6ad27896"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b166de0e62c1cdc2dfa26d287b0e95fad2b939c4"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "86840f71406f3465f4fd6d7c861614f8de9993b38f36a40c819f8c833f0e50d7"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2109b6ed0bd5bf431187ff9ca3e0dcb3fdcad61f"
os = "windows"

    [[NOMAD.download]]
    sha256 = "c7ba65414d5af9face4561d725a39685f5be2863adc6cb497f75f43b1f3be7ee"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c250d3abdb81a5919448a4d54883b5318eb18c37"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "8e3db32152a030c903450281d5af8d2ee1807f61fad6792feb27166868c724ce"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe593f14ce024986abbe7460d42996700154117c"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "0526e2968d73c2c2e24bf8c8674054ad0c6cb8a2642863f1be203b6f11065e88"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "080eca1392f2c12c7dd31627dcf9cca3f238413b"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "24740e127a09edad55f467ce1584e4bb96534c9b38d7e4e720bedb71ceac9a0e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aed155fdaf2709a659fc62c29f73144ae0958f6"
os = "windows"

    [[NOMAD.download]]
    sha256 = "2b8798243951d8e1108e7e73a60078cf908bee4f659a28fc35637f0370b22f5e"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf3c7a4585465fbee12660a9762eca440be1606a"
os = "windows"

    [[NOMAD.download]]
    sha256 = "f5d2450d226b9df7d39ed9d7415d48de75d704989da0b2bd7a781c79551fa985"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b38e35eb53c2ecf749a2c37a9030da276b763118"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b3d0c7b9368ddaed751328bf3c935528b000784e938c010b9f2bfadf18bd87f2"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+1/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
