[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "532607e1818eafc11a001cb1a40eae48d6cb6ba0"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "4cf1af9cbea8e8c6a29508c2e42fd46592f6398846fbdf79f9932ad85d5ef3ff"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da12b4560859085b82c1f8d80ed7d4f358db6dbf"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "8bf70bafeb9dcc141647aea5c886643250e106a91170bc01075d96d12eb7a4b5"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1eb5d21c815c81ae52119cea828e09034ea741f9"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f5c5bbb4f142e4707c82d34023067a9385214a800f6aedbf803881cf15ccacf0"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d3ac2381f3c7aa379ec8c82b244f2c6571c4af0"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "350a94b8dbd50921da663c8139c1ba51e48fd6394214b48877992b8fe875732f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a59094539e962c3912d105bd1bffb1ad1481ab22"
os = "macos"

    [[NOMAD.download]]
    sha256 = "c87157ee873e67790554db653d0cea87c55a21286bf19d288757dfa22126a181"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "271b16245a90424cf3f2bfed20d4dab60d5bcf71"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "0908f7605341f9cc697b69da7b680535b9f32a76ce18e2a0d069b78876a67507"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "806429524ba1f535d6bdae0a4f1fe526425be67c"
os = "windows"

    [[NOMAD.download]]
    sha256 = "fff78264dcbb902bb665d73cc690d23aa93e5341bda0fbe7f37ab0dd9b7f87b6"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a14e90f591b53da28457c286fd4858599ec1adc"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c3195ae36294faeb8f771b7b04e341ff157a8c246e8301f13f24544d936a3d86"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "233f8af468f67805c76b57075d8a674f59ba1be9"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "960f144e4a05365b6aece4cb740db0b2fa8d177d4ff5611c68275cdd7bf0f406"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf59da584d87b372f0bb3d97c21f298d153dd469"
os = "macos"

    [[NOMAD.download]]
    sha256 = "5f737c12b6c6909741e90d43ca2471ac0a98d998472757ec87f9f0fb48dbe4a2"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3601a813068f7f90437e05392da931c43e8ea685"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "3c3f9ec68c5427f8aef5314c42154526fab5c3f14864ae62ce12dc633aa1f2c3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95df8dde4fda057cec8c46fb9b4ac8c5179bbc96"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "727b81563a7ac92b3d3604bc0f7183aca903f94fc05bf3948db4171e5eb5799c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7308a096a2142503a4c4f963206b0d4f2791302a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "5ba843ae3ed9504529597d388f03b32b44c4e26afff838c206142346fcebc680"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e8306c537a32415fae90bc573884718ee7053a2"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "04154892708a1a8e8cd62c3081e89397c7dfd040d4194ec7ef66f02bbf334d3c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "542eda3189d2aa3ff965f1860e367e9085872c7d"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "6935b7df2ce7394bcdbd269c251ee7ddc99eeba4c574be663eb581df569acba3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5be92d2da6abb23d62beb60b73f80bd1454cde7b"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f88b684ce491769e57002d26481c599e2d21113eebd8b553a16be3ed5c0bbc0a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "650a61d04fc32c6776f5e590edbfbbb0b46ff691"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "3c272576b8f2d5e9f5c161cbe1856bd89098efb338d421f27a5a682e42d858c3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f617fc0ceb5522c8e66f11957173ce8e47b7b43a"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "1dd2ecaaf91772410be4268e8073412d3c52d07b28844a3601217332155e73df"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97bfd782e7e79a249badce2a1b0db32b36265d82"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ac0d60ba6511b7422bf939ee0cd5a227fa6215a5a2fca7fb64144865310a4f47"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "008dd0dfbec802d0c282499bb88e428e4b794d8c"
os = "windows"

    [[NOMAD.download]]
    sha256 = "384898b2cded9a2c790d1c714df6edb9e5b1f37adffbdcba8321cca5b218e998"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "343c25c6a41dd912c511d7456b92414dd2210bd8"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "47d64dcf81c29fe23d720359e5d73e366cda8409e74103caa583cc51aea23567"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deefd32f52f6863c9a4301663a67c284aedd68eb"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "35e7f70fe2ee4c1a41a54634b3d5731b47988f9daf42edc3b887d6f356d2e26c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bedce4c5abca2218271f0e6c5604ae06510476a2"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "6717f6c52278fe9c9bb398a8646736d40b3678b622f0116f2a1221879abad9d6"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4866f2cc8c79d5dbf84488d3182f4649d18647fe"
os = "windows"

    [[NOMAD.download]]
    sha256 = "eea1367c0c87668427bfb752852287cafbfce353b7be35ca75897f3ce42d4715"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a647e1ae095d4204d1f345e1784c49b94b6d6fe5"
os = "windows"

    [[NOMAD.download]]
    sha256 = "7dbb7fcb0ea891d2002ba8a25e99c984162aafe5f8dff68b063b9435093d15b2"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07147bf6fe6cf4c2306458467d10578998fcc39e"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "1e710ee896c2ac57dc1b898a71b17dd22bde6012c1cdba1a84556b8bf96a75fa"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.0.0+2/NOMAD.v4.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
