[[NOMAD]]
arch = "aarch64"
git-tree-sha1 = "26bd1b70c324102a9320bdb4b6ec1464d4b73270"
os = "macos"

    [[NOMAD.download]]
    sha256 = "fd12d571bbf69569be5505df0b6d751ee403648553a673e443199d03045e8fa0"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.aarch64-apple-darwin.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd47a3a715c34d16bd9bbe01ca1449b9da20f0d8"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c8264ac67f1b7ae1ec6939bb2948fe5d34637b56608a8490eeb19d253173ff41"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bebae10edfc54e9473c557d741f787bf7cfdface"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "ba295abdfcf1ae646ee528b097b3bc0ad6b147b00e61acc0bb52f1ffc9f1f54a"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d273fb44e13f9c950456bac63a3461a1920fcdd6"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "34053328d19cf3758e5c810538ad59a02f17fca215738debc234ab851a8c0bc9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5094147341b66821a58377b7a9a71a4993cc6024"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "54183b2844c6c4f6f11a542a9d4634b6b2b05e941c12b43af4d824063ecb1608"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b4c4862f3f7a8bb5da529fd155521d7c9c0b78d"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "d5af8e8267cb5ab0c836698da27ab5d1854c30d7c3eb2e3f0b1175a1ef1f4a93"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17540f05de6b2bb668c1dfb16e33050a6e6f07e8"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "f82185b4718ba3b22346091db98431d62d1271961ff3a92aeb322bbffd81c782"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f09c01ceed764c116fac351db34447613dbaf6d3"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "52fe9b33b23f6e47776f891f1efdb13f682678047bd00c801f9a905f80182848"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2a285fea3ea9cf52fc256579a8825d131262cec"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "df07922997bad9bb135c0f828a7da543011baa581eda885afa3e84568631b7e1"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9927dde6d411348138a8333a1a6c93320da1c6e3"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "6b18507a3ccb59dd5551f2da6f60d32f82f225e29467e788f05d20a8bac321a3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aab29697bb754446e04c0c8ef14db54f2cc21962"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c3778a79f819fb317267c35d7c6b8ad1e1c4ab9d344058e348b510eebd9825de"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f11076ca4588addc9ecf35d8c1f2e33cf77b31b"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "af59aa307ed73aac902053dbd937f92e8ce87ad4aea11c854fc3693e7c742f19"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NOMAD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce156f24cb3c5fc435f0f16a34c1693fdceceae6"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "5ebc4af37551614d275621b1d12d8544a58b39d3be47a3ba250aad8385847c9f"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f86462a831ccee71e8fd393a44963f29296db751"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b02ec1574dd9a53b5c1d52625584bf3cbd1294b919fd896f8da51a5b07f9c154"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a899b1ab861d0358471ab49b747b1c7c4f143e13"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "4b2136590e79c1cb4b888abece3a3d5538e05af84e39361369b30322e4fc3994"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43500dbad1e4255c7cc6c732bec72aad8ed8b4ea"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "b082db5a3593bd31dec97bc8c4d8210e9a4f80146093f56ecfc469dc10a314f5"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b9eb178ea361176e8f5317f46104473464984e9"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "2a4c71c9d826939c6af1214f2935fa8df5d9af48bd5a5eba06ac5d09df892312"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "688a1efaeefee7569111991de4cf7e3443158d5b"
os = "windows"

    [[NOMAD.download]]
    sha256 = "6fdfa120e7bf4aeb8f46bae2bf5c6d6995f6fd690feb1443c62be82ba090ccf3"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c31b905a8108781ee0cd92d1b78ceecec90b3da"
os = "windows"

    [[NOMAD.download]]
    sha256 = "24ff191d7a64fcedf98f32fbd7a877e9511ddfe9a501bcc4087b08aab6474dc4"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3eeacd660205e507aa52d8bfd42d8f3f9c4da6b3"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "115d6da09a43fc87fd4a7436ef5f54b423d53cdc934ee4473e84719f8720783b"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "212caa6d3a3af054a6be1b0dd1fbef6ad0ee075e"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "a664084e19f291b6d7d2f7df3344ab98c946bf137502f009760698b1a5c5bf99"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "0bc3f6f5e5cff99a174793649502ec634e852936"
os = "macos"

    [[NOMAD.download]]
    sha256 = "b18fb68a73413da423fb95dab124459fac1dd9414280b5cc4019d28be8b8c089"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-apple-darwin.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8431e8410139778ebe259257a5907c68196000d7"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "fba0ae04cf32f0f339e8dea1808214db772051ac55f51b76027bc6b69fcbeb86"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5481f94a0c36f7c3736a35c4267267c802fb3d04"
libc = "glibc"
os = "linux"

    [[NOMAD.download]]
    sha256 = "c7bccbcd756a4cf741c5646704e48fe1789fb22cc75ed0807cccbc8d3495abf9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0353ac4b102b708df6669e1ba07a30712eef4235"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "039a16478ea39f229e19e5b08574f672f6c78f0bb12ff47953eaeb5f2d4d743c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e81472109d668cd3eee75f06a5848469d56c5f7a"
libc = "musl"
os = "linux"

    [[NOMAD.download]]
    sha256 = "4ee65d85c0685ce6e1181c63bc3e6f65ba8da17a6ebccffd265f72e307b970c9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[NOMAD]]
arch = "x86_64"
git-tree-sha1 = "8ed018c308a7c7bdc4bd3cdc2d1f0b662d4b517e"
os = "freebsd"

    [[NOMAD.download]]
    sha256 = "7beccc5819afd04c3317bf116b7d98863cd76b9b3374d61550a37928038653db"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-unknown-freebsd.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d9b2af3747b2305e12a1e2a809d56436e8988dc"
os = "windows"

    [[NOMAD.download]]
    sha256 = "8f99ac2bb61614fcb367d0067dc739d16bcda6e422f6df014b3e3a1732079a7c"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[NOMAD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbf61a18264f3abb82ad38d088457d845319affa"
os = "windows"

    [[NOMAD.download]]
    sha256 = "2b7a11942470e4fa5871fa4fde6cc17b63c54555ff8aa4bd93ae0f85a49b40c9"
    url = "https://github.com/JuliaBinaryWrappers/NOMAD_jll.jl/releases/download/NOMAD-v4.3.1+0/NOMAD.v4.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
