# Autogenerated wrapper script for NOMAD_jll for x86_64-w64-mingw32-cxx03
export libnomadAlgos, libnomadCInterface, libnomadEval, libnomadUtils, libsgtelib, nomad

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("NOMAD")
JLLWrappers.@declare_library_product(libnomadAlgos, "libnomadAlgos.dll")
JLLWrappers.@declare_library_product(libnomadCInterface, "libnomadCInterface.dll")
JLLWrappers.@declare_library_product(libnomadEval, "libnomadEval.dll")
JLLWrappers.@declare_library_product(libnomadUtils, "libnomadUtils.dll")
JLLWrappers.@declare_library_product(libsgtelib, "libsgtelib.dll")
JLLWrappers.@declare_executable_product(nomad)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libnomadAlgos,
        "bin\\libnomadAlgos.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadCInterface,
        "bin\\libnomadCInterface.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadEval,
        "bin\\libnomadEval.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadUtils,
        "bin\\libnomadUtils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsgtelib,
        "bin\\libsgtelib.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nomad,
        "bin\\nomad.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
